### ISSUE TITLE
Windows build fails with Visual Studio 16.7.0

### ISSUE THREAD

**Issue by gentoo90** [RazrFalcon/tiny-skia#4]
Worked just fine with Visual Studio Community 16.5.2 but started failing after update to 16.7.0.
Also fails on a fresh install of Visual Studio Professional 16.7.0.
```
cargo:warning=In file included from skia/src/core/SkBitmapDevice.cpp:11:
cargo:warning=In file included from skia\include/core/SkPath.h:13:
cargo:warning=skia\include/private/SkPathRef.h(113,41): error: implicit instantiation of undefined template 'std::tuple<SkPoint *, float *>'
cargo:warning=        std::tuple<SkPoint*, SkScalar*> growForVerbsInPath(const SkPathRef& path) {
cargo:warning=                                        ^
cargo:warning=C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.27.29110\include\utility(126,7): note: template is declared here
cargo:warning=class tuple;
cargo:warning=      ^
cargo:warning=In file included from skia/src/core/SkBitmapDevice.cpp:11:
cargo:warning=In file included from skia\include/core/SkPath.h:13:
cargo:warning=skia\include/private/SkPathRef.h(114,30): error: implicit instantiation of undefined template 'std::tuple<SkPoint *, float *>'
cargo:warning=            return fPathRef->growForVerbsInPath(path);
cargo:warning=                             ^
cargo:warning=C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.27.29110\include\utility(126,7): note: template is declared here
cargo:warning=class tuple;
cargo:warning=      ^
cargo:warning=In file included from skia/src/core/SkBitmapDevice.cpp:11:
cargo:warning=skia\include/core/SkPath.h(1542,65): error: implicit instantiation of undefined template 'std::tuple<SkPathVerb, const SkPoint *, const float *>'
cargo:warning=        std::tuple<SkPathVerb, const SkPoint*, const SkScalar*> operator*() const {
cargo:warning=                                                                ^
cargo:warning=C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.27.29110\include\utility(126,7): note: template is declared here
cargo:warning=class tuple;
cargo:warning=      ^
cargo:warning=In file included from skia/src/core/SkBitmapDevice.cpp:11:
cargo:warning=skia\include/core/SkPath.h(1549,20): error: implicit instantiation of undefined template 'std::tuple<SkPathVerb, const SkPoint *, const float *>'
cargo:warning=            return {verb, fPoints + backset, fWeights};
cargo:warning=                   ^
cargo:warning=C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.27.29110\include\utility(126,7): note: template is declared here
cargo:warning=class tuple;
cargo:warning=      ^
cargo:warning=In file included from skia/src/core/SkBitmapDevice.cpp:11:
cargo:warning=skia\include/core/SkPath.h(1624,68): error: implicit instantiation of undefined template 'std::tuple<SkPathVerb, const SkPoint *, const float *>'
cargo:warning=            return (fIter != fEnd) ? static_cast<Verb>(std::get<0>(*fIter)) : kDone_Verb;
cargo:warning=                                                                   ^
cargo:warning=C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.27.29110\include\utility(126,7): note: template is declared here
cargo:warning=class tuple;
cargo:warning=      ^
cargo:warning=5 errors generated.
```
Versions of tools:
* Windows 7 x64 Enterprise
* Visual Studio 2019 (16.7.0) Community and Professional
* rustc 1.45.2 (d3fb005a3 2020-07-31) stable-x86_64-pc-windows-msvc
* cargo 1.45.1 (f242df6ed 2020-07-22)
* LLVM 10.0.0

**Comment by pragmatrix** [comment]
This got fixed upstream with https://github.com/google/skia/commit/0d6f81593b1fa222e8e4afb56cc961ce8c9be375.

**Comment by RazrFalcon** [comment]
@pragmatrix Thanks for a hint.
